import React from "react";
import { StyleSheet, Document, Page, Text, View, Font } from "@react-pdf/renderer";

import Exo from '../fonts/exo.ttf';
import ExoBold from '../fonts/exo-bold.ttf';
import ExoItalic from '../fonts/exo-italic.ttf';

Font.register({
  family: "Exo",
  fonts: [
    { src: Exo },
    { src: ExoBold, fontWeight: "bold" },
    { src: ExoItalic, fontStyle: "italic" }
  ]
})

const styles = StyleSheet.create({
    mainheader: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 10
    },

    sectionheader: {
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 10
    },

    tinyheader: {
      fontSize: 9,
      marginBottom: 10
    },

    question: {
      fontWeight: "bold",
    },

    misc: {
      fontStyle: "italic"
    },

    questiondiv: {
      paddingBottom: 10,
    },

    page: {
      backgroundColor: "#fff",
      fontFamily: "Exo",
      fontSize: 12,
      paddingTop: 50,
      paddingLeft: 50,
      paddingRight: 50,
      paddingBottom: 50,
      lineHeight: 1.5,
      flexDirection: "column"
    }
  });

  const QuestionSheet = ({ questions, username, datetime }) => {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View>
                    <Text style={styles.mainheader}>Quizpedia Question Sheet</Text>
                    <Text style={styles.tinyheader}>Generated by {username} on {datetime}</Text>
                    {questions.map((question, index) => (
                      <View key={index} style={styles.questiondiv}>
                        <Text style={styles.question}>{index + 1}: {question.Question}</Text>
                        <Text>Answer: {question.Answer}</Text>
                        <Text style={styles.misc}>Level: {question.Level} | Species: {question.Species} | Topic: {question.Topic} | Resource: {question.Resource}</Text>
                      </View>
                    ))}
                </View>
            </Page>
        </Document>
    );
  };
  
  export default QuestionSheet;

 